<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>ValidateTests</AssemblyName>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Data\columndelimiter-testfile-1.csv" />
    <None Remove="Data\columndelimiter-testfile-2.csv" />
    <None Remove="Data\columndelimiter-testfile-3.csv" />
    <None Remove="Data\Configuration\configuration.json" />
    <None Remove="Data\Configuration\simplefile-configuration.json" />
    <None Remove="Data\Configuration\testfile-configuration.json" />
    <None Remove="Data\headers-testfile-1.csv" />
    <None Remove="Data\rowterminator-testfile-1.csv" />
    <None Remove="Data\rowterminator-testfile-2.csv" />
    <None Remove="Data\simplefile.csv" />
    <None Remove="Data\singlerow.csv" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Data\columndelimiter-testfile-1.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\columndelimiter-testfile-2.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\columndelimiter-testfile-3.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\Configuration\configuration.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\Configuration\simplefile-configuration.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\Configuration\testfile-configuration.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\headers-testfile-1.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\rowterminator-testfile-1.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\rowterminator-testfile-2.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\simplefile.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\singlerow.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Validate.Lib\Validate.Lib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.0.0" />
    <PackageReference Include="Moq" Version="4.20.70" />
    <PackageReference Include="MSTest.TestFramework" Version="3.0.0" />
  </ItemGroup>

</Project>
